server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: products-route
          uri: lb://PRODUCT-SERVER
          predicates:
            - Path=/products/**
          filters:
            - PrefixPath=/api/v1
eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8762/eureka
